services:
  agenda:
    build: .
    container_name: agenda_node_dev
    restart: always
    ports:
      - "8088:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - agenda_datos:/app/datos

volumes:
  agenda_datos: