services:
  agenda:
    build: .
    container_name: agenda_node_dev
    restart: always
    ports:
      - "8088:3000" # <-- Puerto externo 8088 (El de tu profe) conectado al 3000 de Node
    volumes:
      - .:/app
      - /app/node_modules # Evita sobreescribir dependencias de Linux con las de Windows/Mac
      - agenda_datos:/app/datos # Aísla la base de datos SQLite

volumes:
  agenda_datos: